CREATE TABLE [dbo].[Apoderado]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [NOMBRE] VARCHAR(50) NULL, 
    [TELEFONO] VARCHAR(50) NULL, 
    [id_AlUMNO] INT NULL, 
    CONSTRAINT [FK_Apoderado_ALUMNO] FOREIGN KEY ([id_AlUMNO]) REFERENCES [ALUMNO]([Id]) 
)
